# Generated by Django 3.1 on 2021-03-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(height_field=800, upload_to='files', width_field=400),
        ),
    ]
