# Generated by Django 3.1 on 2021-03-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20210309_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height_field',
            field=models.PositiveIntegerField(default=800),
        ),
        migrations.AddField(
            model_name='image',
            name='width_field',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='files'),
        ),
    ]
