# Generated by Django 3.1 on 2021-03-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20210309_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(height_field='height_field', upload_to='files', width_field='width_field'),
        ),
    ]
