# Generated by Django 3.1 on 2021-03-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20210309_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='height_field',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='width_field',
            new_name='width',
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(height_field='height', upload_to='files', width_field='width'),
        ),
    ]
