# Generated by Django 3.1 on 2021-03-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20210309_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(verbose_name=800),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(verbose_name=400),
        ),
    ]
