# Generated by Django 3.1 on 2021-03-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_auto_20210309_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageSave',
        ),
    ]
