# Generated by Django 3.1 on 2021-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_auto_20210309_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesave',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=400),
        ),
        migrations.AlterField(
            model_name='imagesave',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=800),
        ),
    ]
